title: 'Sean Ng'
description: "Personal website"
logo: 'https://raw.githubusercontent.com/seanywng/seanywng.github.io/master/img/logo_sean_new.png'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal